# Generated by Django 5.2.6 on 2025-10-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='documento_respaldo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='documento_respaldo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
