# Generated by Django 5.2.6 on 2025-12-01 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoapp', '0005_donacion_fecha_donacion_publicacion_hora_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donacion',
            name='id_publicacion',
        ),
        migrations.CreateModel(
            name='DonacionMonetaria',
            fields=[
                ('id_donacion_monetaria', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_donacion', models.DateField(blank=True, null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='proyectoapp.usuario')),
            ],
            options={
                'db_table': 'donacion_monetaria',
            },
        ),
    ]
