# Generated by Django 5.2.6 on 2025-10-13 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id_beneficiario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('comuna', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'beneficiario',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=100)),
                ('tipo_usuario', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Dependiente',
            fields=[
                ('id_dependiente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('edad', models.IntegerField()),
                ('parentesco', models.CharField(blank=True, max_length=50, null=True)),
                ('id_beneficiario', models.ForeignKey(db_column='id_beneficiario', on_delete=django.db.models.deletion.DO_NOTHING, to='proyectoapp.beneficiario')),
            ],
            options={
                'db_table': 'dependiente',
            },
        ),
        migrations.CreateModel(
            name='Municipalidad',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='proyectoapp.usuario')),
                ('nombre_municipalidad', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('comuna', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'municipalidad',
            },
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='proyectoapp.usuario')),
                ('razon_social', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=15)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_entidad', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'organizacion',
            },
        ),
        migrations.CreateModel(
            name='UsuarioNormal',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='proyectoapp.usuario')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario_normal',
            },
        ),
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id_campana', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='proyectoapp.usuario')),
            ],
            options={
                'db_table': 'campana',
            },
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='id_usuario_cuenta',
            field=models.ForeignKey(blank=True, db_column='id_usuario_cuenta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='beneficiario_id_usuario_cuenta_set', to='proyectoapp.usuario'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='id_usuario_registrador',
            field=models.ForeignKey(db_column='id_usuario_registrador', on_delete=django.db.models.deletion.DO_NOTHING, to='proyectoapp.usuario'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('mensaje', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('leido', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='proyectoapp.usuario')),
            ],
            options={
                'db_table': 'notificacion',
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id_publicacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo_publicacion', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='proyectoapp.usuario')),
            ],
            options={
                'db_table': 'publicacion',
            },
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id_donacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_expiracion', models.DateField(blank=True, null=True)),
                ('id_publicacion', models.ForeignKey(db_column='id_publicacion', on_delete=django.db.models.deletion.DO_NOTHING, to='proyectoapp.publicacion')),
            ],
            options={
                'db_table': 'donacion',
            },
        ),
        migrations.CreateModel(
            name='ApoyoBeneficiario',
            fields=[
                ('id_apoyo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_apoyo', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('id_beneficiario', models.ForeignKey(db_column='id_beneficiario', on_delete=django.db.models.deletion.DO_NOTHING, to='proyectoapp.beneficiario')),
                ('id_publicacion', models.ForeignKey(blank=True, db_column='id_publicacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='proyectoapp.publicacion')),
            ],
            options={
                'db_table': 'apoyo_beneficiario',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('id_beneficiario', models.ForeignKey(db_column='id_beneficiario', on_delete=django.db.models.deletion.DO_NOTHING, to='proyectoapp.beneficiario')),
                ('id_publicacion', models.ForeignKey(db_column='id_publicacion', on_delete=django.db.models.deletion.DO_NOTHING, to='proyectoapp.publicacion')),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
        migrations.CreateModel(
            name='ApoyoMunicipal',
            fields=[
                ('id_apoyo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_apoyo', models.CharField(max_length=30)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_apoyo', models.DateField(blank=True, null=True)),
                ('id_publicacion', models.ForeignKey(db_column='id_publicacion', on_delete=django.db.models.deletion.DO_NOTHING, to='proyectoapp.publicacion')),
                ('id_municipalidad', models.ForeignKey(db_column='id_municipalidad', on_delete=django.db.models.deletion.DO_NOTHING, to='proyectoapp.municipalidad')),
            ],
            options={
                'db_table': 'apoyo_municipal',
            },
        ),
    ]
