# Generated by Django 5.2.6 on 2025-11-10 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoapp', '0003_hash_existing_passwords'),
        ('proyectoapp', '0003_usuario_es_admin'),
    ]

    operations = [
    ]
