# Generated by Django 5.2.6 on 2025-11-11 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoapp', '0004_merge_20251110_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='fecha_donacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='proyectoapp.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(max_length=128),
        ),
    ]
